version: "3.9"
services:
  binotify-premium:
    hostname: binotify-premium
    build: .
    env_file: .env
    container_name: binotify-premium
    ports:
      - "10000:3000"
    volumes:
      - ./src:/app/src
