version: "3.9"
services:
  binotify-premium-app:
    container_name: binotify-premium-app
    hostname: binotify-premium-app
    build: .
    env_file: .env
    ports:
      - "10000:10000"
    volumes:
      - ./src:/app/src
