export const GET_SONGS = 'GET_SONGS';
export const UPDATE_SONGS = 'UPDATE_SONGS';
export const DELETE_SONG = 'DELETE_SONG';
export const UPDATE_SONG = 'UPDATE_SONG';
export const SUCCESS_UPDATE_SONG = 'SUCCESS_UPDATE_SONG';
export const FAILED_UPDATE_SONG = 'FAILED_UPDATE_SONG';