export const GET_USER = 'GET_USER'
export const SET_USER = 'SET_USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const REMOVE_USER = 'REMOVE_USER'