export const GET_REQUESTS = 'GET_REQUESTS';
export const UPDATE_REQUESTS = 'UPDATE_REQUESTS';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const DESICION_REQUEST_FAILED = 'DESICION_REQUEST_FAILED';